#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build JDC-Padavan

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo -E apt update
          sudo -E apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd cpio git python-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clone source code
        run: |
          git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u

      - name: Download Toolchain
        run: |
          sudo -E chmod -R 777 /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sudo -E mkdir -p toolchain-3.4.x
          wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
          sudo -E tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x

      - name: Load custom configuration
        run: |
          cp -f -r Padavan/JDC/ /opt/rt-n56u/trunk/configs/boards/JDC
          cp -f Padavan/JDC.config /opt/rt-n56u/trunk/configs/templates
          cp -f Padavan/JDC-5.0.config /opt/rt-n56u/trunk/configs/templates

      - name: Build Firmware
        env:
          TNAME: JDC
        run: |
          mkdir -p /opt/images/
          cd /opt/rt-n56u/trunk
          sudo ./clear_tree
          sudo ./build_firmware_modify $TNAME
          sudo mv -f images/*.trx /opt/images/
      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: JDC-Padavan
          path: /opt/images
